name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  BUILD_DIR_PREFIX: _build

jobs:

  #
  # Cookiecutter project generation test
  #
  test-generated-project:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [intel]

    steps:

      - name: Check-out code
        uses: actions/checkout@v4

      - name: Setup Intel compiler
        uses: rscohn2/setup-oneapi@v0
        with:
          components: |
            ifx
            impi

      - name: Setup Intel environment
        run: |
          source /opt/intel/oneapi/setvars.sh
          printenv >> ${GITHUB_ENV}
          echo "FC=ifx" >> ${GITHUB_ENV}
          echo "FPM_FC=ifx" >> ${GITHUB_ENV}

      - name: Setup build tools
        run: |
          pip install cookiecutter cmake ninja fpm

      - name: Test CMake serial
        run: |
          ./test/runners/test.cmake-serial.sh ${BUILD_DIR_PREFIX}_cmake_serial

      - name: Test CMake MPI
        run: |
          ./test/runners/test.cmake-mpi.sh ${BUILD_DIR_PREFIX}_cmake_mpi

      - name: Test CMake coarray
        run: |
          ./test/runners/test.cmake-coarray.sh ${BUILD_DIR_PREFIX}_cmake_coarray

      - name: Test Fpm serial
        run: |
          ./test/runners/test.fpm-serial.sh ${BUILD_DIR_PREFIX}_fpm_serial

      - name: Test Fpm MPI
        run: |
          FPM_FFLAGS="-stand f18" ./test/runners/test.fpm-mpi.sh ${BUILD_DIR_PREFIX}_fpm_mpi

      - name: Test Fpm coarray
        run: |
          FPM_FFLAGS="-coarray" FPM_LDFLAGS="-coarray" ./test/runners/test.fpm-coarray.sh ${BUILD_DIR_PREFIX}_fpm_coarray
